# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='echo_service.proto',
  package='',
  serialized_pb='\n\x12\x65\x63ho_service.proto\"\x18\n\x0b\x45\x63hoRequest\x12\t\n\x01i\x18\x01 \x02(\x05\"\x1e\n\x0c\x45\x63hoResponse\x12\x0e\n\x06\x65\x63hoed\x18\x01 \x02(\x05\x32\x32\n\x0b\x45\x63hoService\x12#\n\x04\x45\x63ho\x12\x0c.EchoRequest\x1a\r.EchoResponseB\x06\x80\x01\x01\x90\x01\x01')




_ECHOREQUEST = descriptor.Descriptor(
  name='EchoRequest',
  full_name='EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='i', full_name='EchoRequest.i', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=46,
)


_ECHORESPONSE = descriptor.Descriptor(
  name='EchoResponse',
  full_name='EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='echoed', full_name='EchoResponse.echoed', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE

class EchoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOREQUEST
  
  # @@protoc_insertion_point(class_scope:EchoRequest)

class EchoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHORESPONSE
  
  # @@protoc_insertion_point(class_scope:EchoResponse)


_ECHOSERVICE = descriptor.ServiceDescriptor(
  name='EchoService',
  full_name='EchoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=80,
  serialized_end=130,
  methods=[
  descriptor.MethodDescriptor(
    name='Echo',
    full_name='EchoService.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    options=None,
  ),
])

class EchoService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ECHOSERVICE
class EchoService_Stub(EchoService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ECHOSERVICE

# @@protoc_insertion_point(module_scope)
