# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='dom_channel.proto',
  package='',
  serialized_pb='\n\x11\x64om_channel.proto\"\x9c\x01\n\x0eInvoke_Request\x12%\n\x1dmessage_full_name_fingerprint\x18\x01 \x02(\x04\x12\x17\n\x0fkey_fingerprint\x18\x02 \x02(\x04\x12\x1c\n\x14location_fingerprint\x18\x03 \x02(\x04\x12\x13\n\x0bretry_count\x18\x04 \x02(\r\x12\x17\n\x0fmessage_content\x18\x05 \x02(\x0c\"I\n\x0fInvoke_Response\x12\x12\n\nerror_code\x18\x01 \x02(\x05\x12\x13\n\x0bretry_count\x18\x02 \x02(\x05\x12\r\n\x05retry\x18\x03 \x02(\x08\x32\x39\n\nDOMService\x12+\n\x06Invoke\x12\x0f.Invoke_Request\x1a\x10.Invoke_ResponseB\x06\x80\x01\x01\x90\x01\x01')




_INVOKE_REQUEST = descriptor.Descriptor(
  name='Invoke_Request',
  full_name='Invoke_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_full_name_fingerprint', full_name='Invoke_Request.message_full_name_fingerprint', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key_fingerprint', full_name='Invoke_Request.key_fingerprint', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location_fingerprint', full_name='Invoke_Request.location_fingerprint', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='retry_count', full_name='Invoke_Request.retry_count', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message_content', full_name='Invoke_Request.message_content', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=178,
)


_INVOKE_RESPONSE = descriptor.Descriptor(
  name='Invoke_Response',
  full_name='Invoke_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error_code', full_name='Invoke_Response.error_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='retry_count', full_name='Invoke_Response.retry_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='retry', full_name='Invoke_Response.retry', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=180,
  serialized_end=253,
)

DESCRIPTOR.message_types_by_name['Invoke_Request'] = _INVOKE_REQUEST
DESCRIPTOR.message_types_by_name['Invoke_Response'] = _INVOKE_RESPONSE

class Invoke_Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVOKE_REQUEST
  
  # @@protoc_insertion_point(class_scope:Invoke_Request)

class Invoke_Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVOKE_RESPONSE
  
  # @@protoc_insertion_point(class_scope:Invoke_Response)


_DOMSERVICE = descriptor.ServiceDescriptor(
  name='DOMService',
  full_name='DOMService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=255,
  serialized_end=312,
  methods=[
  descriptor.MethodDescriptor(
    name='Invoke',
    full_name='DOMService.Invoke',
    index=0,
    containing_service=None,
    input_type=_INVOKE_REQUEST,
    output_type=_INVOKE_RESPONSE,
    options=None,
  ),
])

class DOMService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _DOMSERVICE
class DOMService_Stub(DOMService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _DOMSERVICE

# @@protoc_insertion_point(module_scope)
