# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='lockservice.proto',
  package='lockservice',
  serialized_pb='\n\x11lockservice.proto\x12\x0blockservice\"d\n\x07Request\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x18\n\rmax_wait_time\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x05token\x18\x03 \x01(\x03:\x01\x30\x12\x0f\n\x05value\x18\x04 \x01(\t:\x00\x12\x0f\n\x04\x66lag\x18\x05 \x01(\x05:\x01\x30\"L\n\x08Response\x12\x0e\n\x06result\x18\x01 \x02(\x05\x12\x0f\n\x05value\x18\x02 \x01(\t:\x00\x12\r\n\x03key\x18\x03 \x01(\t:\x00\x12\x10\n\x05token\x18\x04 \x01(\x03:\x01\x30\x32\xd2\x02\n\x0bLockService\x12\x33\n\x04Read\x12\x14.lockservice.Request\x1a\x15.lockservice.Response\x12\x34\n\x05Write\x12\x14.lockservice.Request\x1a\x15.lockservice.Response\x12\x33\n\x04Lock\x12\x14.lockservice.Request\x1a\x15.lockservice.Response\x12\x35\n\x06Unlock\x12\x14.lockservice.Request\x1a\x15.lockservice.Response\x12\x35\n\x06\x43reate\x12\x14.lockservice.Request\x1a\x15.lockservice.Response\x12\x35\n\x06\x44\x65lete\x12\x14.lockservice.Request\x1a\x15.lockservice.ResponseB\x06\x80\x01\x01\x90\x01\x01')




_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='lockservice.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='lockservice.Request.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_wait_time', full_name='lockservice.Request.max_wait_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='lockservice.Request.token', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='lockservice.Request.value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flag', full_name='lockservice.Request.flag', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=134,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='lockservice.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='lockservice.Response.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='lockservice.Response.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='lockservice.Response.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='lockservice.Response.token', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:lockservice.Request)

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:lockservice.Response)


_LOCKSERVICE = descriptor.ServiceDescriptor(
  name='LockService',
  full_name='lockservice.LockService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=215,
  serialized_end=553,
  methods=[
  descriptor.MethodDescriptor(
    name='Read',
    full_name='lockservice.LockService.Read',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Write',
    full_name='lockservice.LockService.Write',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Lock',
    full_name='lockservice.LockService.Lock',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Unlock',
    full_name='lockservice.LockService.Unlock',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Create',
    full_name='lockservice.LockService.Create',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Delete',
    full_name='lockservice.LockService.Delete',
    index=5,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])

class LockService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _LOCKSERVICE
class LockService_Stub(LockService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _LOCKSERVICE

# @@protoc_insertion_point(module_scope)
